name: CI

on:
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - '*'

jobs:
  unit-tests:
    name: 'Unit Tests'
    runs-on: 'ubuntu-latest'
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Redis
        run: docker run --name redis -d -p 6379:6379 redis

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Run Tests
        env:
          REDIS_ADDRESS: 'localhost:6379'
        run: go test -v -timeout 300s -covermode atomic -coverprofile=covprofile ./...

      - name: Upload Coverage Report
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GO111MODULE: off
        run: |
          go get github.com/mattn/goveralls
          goveralls -coverprofile=covprofile -service=github